# Librarie pour les thumbnails => générer des images plus petites pour optimiser la perf
# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        squared_thumbnail_small:
            filters:
                #outbound = resulting image to be cropped if the input ratio differs
                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true }
        squared_thumbnail_medium:
            filters:
                thumbnail: { size: [500, 500], mode: outbound, allow_upscale: true }